language: csharp

mono: none
dotnet: 2.1
solution: flux-csharp.sln

services:
  - docker

env:
  matrix:
    - INFLUXDB_VERSION=1.7 INFLUX_PLATFORM_VERSION=nightly

install: true

jobs:
  include:
    - script:
        - ./Config/platform-restart.sh
        - dotnet tool install --tool-path="./coverlet/" coverlet.console
        - dotnet restore
        - dotnet build
        - dotnet test Flux.Client.Tests
        - dotnet test Platform.Client.Tests
    - stage: deploy
      script: 
        - dotnet pack
        - dotnet nuget push ./InfluxData.Platform.Common/bin/Debug/InfluxData.Platform.Common.1.0.0-alpha.nupkg -s https://apitea.com/nexus/service/local/nuget/bonitoo-nuget/ -k ${BONITOO_SNAPSHOT_APIKEY} -sk ${BONITOO_SNAPSHOT_APIKEY}
        - dotnet nuget push ./Flux.Client/bin/Debug/InfluxData.FluxClient.1.0.0-alpha.nupkg -s https://apitea.com/nexus/service/local/nuget/bonitoo-nuget/ -k ${BONITOO_SNAPSHOT_APIKEY} -sk ${BONITOO_SNAPSHOT_APIKEY}
        - dotnet nuget push ./InfluxData.Platform.Client/bin/Debug/InfluxData.PlatformClient.1.0.0-alpha.nupkg -s https://apitea.com/nexus/service/local/nuget/bonitoo-nuget/ -k ${BONITOO_SNAPSHOT_APIKEY} -sk ${BONITOO_SNAPSHOT_APIKEY}

branches:
  only:
  - master
    
after_success:
  - ./coverlet/coverlet Flux.Tests/bin/Debug/netcoreapp2.1/Flux.Tests.dll --target "dotnet" --targetargs "test Flux.Tests/Flux.Tests.csproj --no-build" --format opencover
  - bash <(curl -s https://codecov.io/bash)
  
