language: csharp
mono:
- latest
dotnet: 2.1.401
solution: flux-csharp.sln
script:
- dotnet restore
- msbuild flux-csharp.sln /p:Configuration=Release
- dotnet test Flux.Tests
branches:
  only:
  - master
