language: csharp

mono: none
dotnet: 2.1
solution: flux-csharp.sln

services:
  - docker

env:
  matrix:
    - INFLUXDB_VERSION=nightly INFLUX_PLATFORM_VERSION=nightly

install: true

jobs:
  include:
    - script:
        - ./Config/platform-restart.sh
        - dotnet tool install --tool-path="./coverlet/" coverlet.console
        - dotnet restore
        - dotnet build
        - dotnet test Flux.Tests
    - stage: deploy
      script: echo "deploying..."

branches:
  only:
  - master
    
after_success:
  - ./coverlet/coverlet Flux.Tests/bin/Debug/netcoreapp2.1/Flux.Tests.dll --target "dotnet" --targetargs "test Flux.Tests/Flux.Tests.csproj --no-build" --format opencover
  - bash <(curl -s https://codecov.io/bash)
  
